// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

type PrismaConfig = {
  schema: string;
  migrations?: {
    path: string;
  };
  datasource?: {
    url?: string;
  };
};

const defineConfig = (config: PrismaConfig) => config;
const env = (variable: string) => process.env[variable];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
